services:
  tunnel:
    container_name: !reset null
    restart: !reset null
    pull_policy: !reset null
    env_file: !reset []
    environment: []
    command: tunnel --metrics 0.0.0.0:2000 run --token-file /run/secrets/cloudflare_tunnel_token
    secrets:
      - source: cf_tunnel_token_dev_v1
        target: cloudflare_tunnel_token
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 2m
      placement:
        constraints:
          - node.labels.app_zone == manager

secrets:
  cf_tunnel_token_dev_v1:
    external: true
    name: cf_tunnel_token_dev_v1
