name: App Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  pull-requests: read

jobs:
  ci-and-deploy:
    uses: pinokew/shared-workflows/.github/workflows/shared-ci-cd.yml@main
    with:
      environment_name: ${{ github.ref == 'refs/heads/dev' && 'development' || 'production' }}
      deploy: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main') }}
      use_ansible: false
      build_and_push_docker: false
    secrets: inherit

