name: App Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  pull-requests: read

jobs:
  ci-checks:
    uses: pinokew/shared-workflows/.github/workflows/shared-ci-cd.yml@main
    with:
      environment_name: 'dummy'  # не використовується в ci-checks
      deploy: false               # disable deploy для ci-checks job
      use_ansible: false
      build_and_push_docker: false
    secrets:
      TS_OAUTH_CLIENT_ID: ''
      TS_OAUTH_SECRET: ''
      SERVER_HOST: ''
      SERVER_USER: ''
      SERVER_SSH_KEY: ''
      SSH_HOST_KEY_PUB: ''
      DEPLOY_PROJECT_DIR: ''

  deploy:
    needs: ci-checks
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    uses: pinokew/shared-workflows/.github/workflows/shared-ci-cd.yml@main
    with:
      environment_name: 'development'
      deploy: true
      use_ansible: false
      build_and_push_docker: false
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      SSH_HOST_KEY_PUB: ${{ secrets.SSH_HOST_KEY_PUB }}
      DEPLOY_PROJECT_DIR: ${{ secrets.DEPLOY_PROJECT_DIR }}

